### ISSUE TITLE
'pyenv virtualenvs' broken

### ISSUE THREAD

**Issue by p-baum** [ayr-ton/PKGBUILDs#16]
$ pyenv virtualenvs
/usr/bin/pyenv-virtualenvs: line 10: /usr/bin/../libexec/pyenv-virtualenv-realpath: No such file or directory

**Comment by p-baum** [comment]
wrong command: should be 'pyenv virtualenv virtualenvs'

**Comment by ayr-ton** [comment]
Let me know if I can provide any further assistance on this on the case you see any new issue.
